# chapter 1

## 벡터, 행렬, 배열

In [2]:
import numpy as np 
vector_row = np.array([1,2,3])

In [3]:
new_row = vector_row.copy()
new_row is vector_row

False

In [4]:
matrix  = np.array([[1,2],[1,2],[1,2]])

In [1]:
import numpy as np
zero_matrix = np.zeros((3,2))

In [2]:
zero_matrix

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [3]:
seven_matrix = np.full((3,2),7)

In [5]:
seven_matrix

array([[7, 7],
       [7, 7],
       [7, 7]])

## 희소 행렬

In [7]:
from scipy import sparse

matrix = np.array([[0,0],
                 [0,1],
                 [3,0]])
matrix_sparse = sparse.csr_matrix(matrix)

In [8]:
matrix_sparse

<3x2 sparse matrix of type '<class 'numpy.intc'>'
	with 2 stored elements in Compressed Sparse Row format>

In [9]:
print(matrix_sparse)


  (1, 1)	1
  (2, 0)	3


### (data, (row_index, col_index)) 로 구성된 튜플을 전달


In [15]:
matrix_sparse_2 = sparse.csr_matrix(([1,3],([1,2],[1,0])),shape=(3,10))

In [16]:
print(matrix_sparse_2)

  (1, 1)	1
  (2, 0)	3


In [18]:
print(matrix_sparse_2.toarray())

[[0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [3 0 0 0 0 0 0 0 0 0]]


In [19]:
matrix_sparse_2.todense()

matrix([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
        [3, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)

## 원소 선택하기

In [20]:
vector = np.array([1,2,3,4,5,6])
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [21]:
vector[:]

array([1, 2, 3, 4, 5, 6])

In [22]:
vector[:3]

array([1, 2, 3])

In [23]:
vector[3:]

array([4, 5, 6])

In [24]:
vector[-1]

6

In [25]:
matrix[:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
matrix[:,1:2]

array([[2],
       [5],
       [8]])

In [27]:
matrix[[0,2]]

array([[1, 2, 3],
       [7, 8, 9]])

In [28]:
matrix[[0,2],[1,0]]

array([2, 7])

In [29]:
matrix[[0,1,1],[2,1,1]]

array([3, 5, 5])

In [30]:
maks = matrix > 5

In [31]:
maks


array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [32]:
matrix[maks]

array([6, 7, 8, 9])

## 행렬 정보 확인하기


In [35]:
matrix = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [37]:
matrix.shape

(3, 4)

In [38]:
matrix.ndim

2

In [39]:
add_100 = lambda i : i+ 100

vectorize_add_100 = np.vectorize(add_100)

In [41]:
vectorize_add_100(matrix)

array([[101, 102, 103, 104],
       [105, 106, 107, 108],
       [109, 110, 111, 112]])

In [42]:
np.min(matrix)

1

In [43]:
np.max(matrix)

12

In [48]:
np.min(matrix, axis = 0)

array([1, 2, 3, 4])

In [49]:
np.mean(matrix)

6.5

In [50]:
np.var(matrix)

11.916666666666666

In [52]:
np.std(matrix, ddof= 1)

3.605551275463989

## 배열 크기 바꾸기

In [53]:
matrix.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

## 벡터나 행렬 전치하기

In [55]:
matrix.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [56]:
matrix.T


array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [57]:
np.array([1,2,3,4,5,6]).T

array([1, 2, 3, 4, 5, 6])

In [58]:
np.array([[1,2,3,4,5,6]]).T

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [59]:
matrix

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [61]:
matrix.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

#### reshape는 뷰를 반환 ,  flatten은 새로운 배열은 만든다.

In [62]:
vector_reshpaed = matrix.reshape(-1)
vector_flattened = matrix.flatten()

In [63]:
matrix[0][0] = -1

In [65]:
vector_reshpaed

array([-1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [68]:
vector_flattened

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [69]:
matrix.ndim

2

## 행렬의 랭크 구하기

In [70]:
np.linalg.matrix_rank(matrix)

3

In [71]:
matrix

array([[-1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

## 행렬식 계산하기

In [73]:
matrix = np.array([[1,2,3],[2,4,6],[3,8,9]])

In [74]:
np.linalg.det(matrix)

0.0

## 행렬의 대각원소 구하기

In [75]:
matrix.diagonal()

array([1, 4, 9])

In [76]:
a= matrix.diagonal().copy()

In [77]:
a = np.diag(matrix)

In [78]:
print(a)

[1 4 9]


In [79]:
a

array([1, 4, 9])

In [80]:
np.diag(a)

array([[1, 0, 0],
       [0, 4, 0],
       [0, 0, 9]])

In [82]:
sum(matrix.diagonal())

14

In [83]:
matrix.trace()

14

## 점곱 계산하기

In [85]:
vector_a = np.array([1,2,3])
vector_b = np.array([4,5,6])

In [86]:
np.dot(vector_a , vector_b)

32

In [87]:
vector_a @ vector_b

32

In [89]:
matrix_a = np.array([[1,1,1],[1,1,1],[1,1,2]])
matrix_b = np.array([[1,3,1],
                    [1,3,1],
                    [1,3,8]])

In [90]:
np.add(matrix_a , matrix_b)

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

In [91]:
np.subtract(matrix_a, matrix_b)

array([[ 0, -2,  0],
       [ 0, -2,  0],
       [ 0, -2, -6]])

In [92]:
np.subtract(matrix_b, matrix_a)

array([[0, 2, 0],
       [0, 2, 0],
       [0, 2, 6]])

## 행렬 곱셈

In [93]:
matrix_a = np.array([[1,1],
                     [1,2]])
matrix_b = np.array([[1,3],
                    [1,2]])

In [94]:
np.dot(matrix_a, matrix_b)

array([[2, 5],
       [3, 7]])

In [95]:
matrix_a * matrix_b

array([[1, 3],
       [1, 4]])

In [97]:
matrix = np.array([[1,4],
                 [2,5]])

In [98]:
np.linalg.inv(matrix)

array([[-1.66666667,  1.33333333],
       [ 0.66666667, -0.33333333]])

In [99]:
np.dot(matrix, np.linalg.inv(matrix))

array([[1., 0.],
       [0., 1.]])

## 난수 생성하기


In [105]:
np.random.seed(0)

In [103]:
np.random.random(3)

array([0.5488135 , 0.71518937, 0.60276338])

In [108]:
np.random.randint(0,11,3)

array([0, 5, 3])

In [110]:
np.random.normal((2,3))

array([1.53995788, 2.94207916])

In [111]:
np.random.normal(0.0, 1.0, (2,3))

array([[ 2.07757414, -0.60131248,  0.93923639],
       [-1.18040862, -0.34733018,  0.06629873]])

In [113]:
np.random.standard_normal((2,3))

array([[-1.62758528,  0.39788586, -1.62915743],
       [-0.63893553, -0.56080987,  1.81898259]])

In [114]:
np.random.choice(3,5)

array([0, 1, 0, 1, 0])

In [115]:
a=np.array([1,2,3,4,5])


In [116]:
np.random.shuffle(a)

In [117]:
a

array([4, 1, 3, 5, 2])

In [118]:
np.random.permutation(a)

array([1, 4, 3, 5, 2])

In [119]:
a

array([4, 1, 3, 5, 2])

In [120]:
np.random.permutation(7)

array([4, 3, 5, 6, 2, 1, 0])