## 레몬에이드 판매랑 예측

In [ ]:
# 라이브러리 사용
import tensorflow as tf
import pandas as pd


In [ ]:
#데이터를 준비합니다.
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/lemonade.csv'
레몬에이드  = pd.read_csv(파일경로)
레몬에이드.head()

온도  판매량
0  20   40
1  21   42
2  22   44
3  23   46
4  24   48

In [ ]:
#독립변수 , 종속변수

독립 = 레몬에이드[['온도']]
종속 = 레몬에이드[['판매량']]
print(독립.shape, 종속.shape)

(6, 1) (6, 1)


In [ ]:
#모델을 만듭니다.
X = tf.keras.layers.Input(1)
Y = tf.keras.layers.Dense(1)(X)
model = tf.keras.models.Model(X,Y)
model.compile(loss='mse')

In [ ]:
#모델을 학습시킨다.
model.fit(독립,종속,epochs=1000,verbose=0)
model.fit(독립, 종속,epochs=10)

Epoch 1/10
1/1 [==============================] - 0s 5ms/step - loss: 0.0043
Epoch 2/10
1/1 [==============================] - 0s 6ms/step - loss: 0.0043
Epoch 3/10
1/1 [==============================] - 0s 3ms/step - loss: 0.0043
Epoch 4/10
1/1 [==============================] - 0s 4ms/step - loss: 0.0043
Epoch 5/10
1/1 [==============================] - 0s 3ms/step - loss: 0.0043
Epoch 6/10
1/1 [==============================] - 0s 7ms/step - loss: 0.0043
Epoch 7/10
1/1 [==============================] - 0s 3ms/step - loss: 0.0043
Epoch 8/10
1/1 [==============================] - 0s 7ms/step - loss: 0.0043
Epoch 9/10
1/1 [==============================] - 0s 5ms/step - loss: 0.0043
Epoch 10/10
1/1 [==============================] - 0s 4ms/step - loss: 0.0043


In [ ]:
#모델을 이용한다.
print(model.predict(독립))

[[40.109386]
 [42.07219 ]
 [44.034992]
 [45.997795]
 [47.960594]
 [49.923397]]


In [ ]:
print(종속)

   판매량
0   40
1   42
2   44
3   46
4   48
5   50


In [ ]:
print(model.predict([[15]]))

[[30.295372]]


## 보스턴 집값 예측

In [ ]:
#라이브러리 사용
import pandas as pd
import tensorflow as tf

In [ ]:
#과거의 데이터를 준비한다.
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv'
보스턴 = pd.read_csv(파일경로)
print(보스턴.columns)
보스턴.head()

Index(['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat', 'medv'],
      dtype='object')


crim    zn  indus  chas    nox  ...  tax  ptratio       b  lstat  medv
0  0.00632  18.0   2.31     0  0.538  ...  296     15.3  396.90   4.98  24.0
1  0.02731   0.0   7.07     0  0.469  ...  242     17.8  396.90   9.14  21.6
2  0.02729   0.0   7.07     0  0.469  ...  242     17.8  392.83   4.03  34.7
3  0.03237   0.0   2.18     0  0.458  ...  222     18.7  394.63   2.94  33.4
4  0.06905   0.0   2.18     0  0.458  ...  222     18.7  396.90   5.33  36.2

[5 rows x 14 columns]

In [ ]:
#독립변수, 종속변수
독립 = 보스턴[['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat']]
종속 = 보스턴[['medv']]
print(독립.shape, 종속.shape)

(506, 13) (506, 1)


In [ ]:
#모델의 구조를 만든다.
X = tf.keras.layers.Input(13)
Y = tf.keras.layers.Dense(1)(X)
model = tf.keras.models.Model(X,Y)
model.compile(loss='mse')

In [ ]:
#모델을 학습시킨다.(Fit)
model.fit(독립,종속, epochs=500,verbose= 0)
model.fit(독립, 종속, epochs= 10)

Epoch 1/10
16/16 [==============================] - 0s 1ms/step - loss: 23.6378
Epoch 2/10
16/16 [==============================] - 0s 1ms/step - loss: 23.7514
Epoch 3/10
16/16 [==============================] - 0s 1ms/step - loss: 23.8347
Epoch 4/10
16/16 [==============================] - 0s 1ms/step - loss: 23.6071
Epoch 5/10
16/16 [==============================] - 0s 1ms/step - loss: 23.9537
Epoch 6/10
16/16 [==============================] - 0s 1ms/step - loss: 23.7161
Epoch 7/10
16/16 [==============================] - 0s 1ms/step - loss: 23.8791
Epoch 8/10
16/16 [==============================] - 0s 1ms/step - loss: 24.1867
Epoch 9/10
16/16 [==============================] - 0s 1ms/step - loss: 23.4393
Epoch 10/10
16/16 [==============================] - 0s 969us/step - loss: 23.5384


In [ ]:
#모델을 이용한다.
print(model.predict(독립[:5]))
print(종속[:5])

[[29.682615]
 [24.559471]
 [31.009617]
 [29.578037]
 [29.197813]]
   medv
0  24.0
1  21.6
2  34.7
3  33.4
4  36.2


In [ ]:
print(model.get_weights())

[array([[-0.09743206],
       [ 0.04865482],
       [-0.01937436],
       [ 2.6422584 ],
       [-3.3988943 ],
       [ 5.1753354 ],
       [-0.01062712],
       [-1.0966204 ],
       [ 0.20559001],
       [-0.012383  ],
       [-0.5493546 ],
       [ 0.01104219],
       [-0.46871224]], dtype=float32), array([10.234005], dtype=float32)]


# 아이리스 품종 분류

In [ ]:
# 라이브러리 사용
import pandas as pd
import tensorflow as tf

In [ ]:
#과거의 데이터를 준비한다.
파일경로 ='https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
아이리스 = pd.read_csv(파일경로)
아이리스.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa

In [ ]:
#원핫인코딩
인코딩 = pd.get_dummies(아이리스)
인코딩.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0   5.1  3.5    1.4   0.2          1              0             0
1   4.9  3.0    1.4   0.2          1              0             0
2   4.7  3.2    1.3   0.2          1              0             0
3   4.6  3.1    1.5   0.2          1              0             0
4   5.0  3.6    1.4   0.2          1              0             0

In [ ]:
print(인코딩.columns)

Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종_setosa', '품종_versicolor',
       '품종_virginica'],
      dtype='object')


In [ ]:
#독립변수, 종속변수
독립 = 인코딩[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속 = 인코딩[['품종_setosa', '품종_versicolor','품종_virginica']]

print(독립.shape, 종속.shape)

(150, 4) (150, 3)


In [ ]:
#모델의 구조를 만듭니다.
X = tf.keras.layers.Input(shape=[4])
Y = tf.keras.layers.Dense(3,activation = 'softmax')(X)
model = tf.keras.models.Model(X,Y)
model.compile(loss ='categorical_crossentropy', metrics ='accuracy')

In [ ]:
#모델을 학습시킨다.
model.fit(독립, 종속, epochs = 100, verbose = 0)
model.fit(독립, 종속, epochs= 10)

Epoch 1/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1374 - accuracy: 0.9733
Epoch 2/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1376 - accuracy: 0.9733
Epoch 3/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1371 - accuracy: 0.9733
Epoch 4/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1370 - accuracy: 0.9733
Epoch 5/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1367 - accuracy: 0.9733
Epoch 6/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1372 - accuracy: 0.9667
Epoch 7/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1370 - accuracy: 0.9733
Epoch 8/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1369 - accuracy: 0.9733
Epoch 9/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1365 - accuracy: 0.9733
Epoch 10/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1369 - accuracy: 0.9733


In [ ]:
#모델을 이용합니다.
print(model.predict(독립[:5]))

[[9.9957746e-01 4.2255421e-04 7.0748545e-09]
 [9.9771500e-01 2.2848663e-03 1.0707292e-07]
 [9.9917740e-01 8.2260149e-04 2.9962212e-08]
 [9.9772316e-01 2.2767116e-03 1.4151813e-07]
 [9.9969947e-01 3.0054903e-04 4.7413780e-09]]


In [ ]:
print(종속[:5])

   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0


In [ ]:
print(model.predict(독립[-5:]))
print(종속[-5:])

[[1.0693319e-07 6.2595889e-02 9.3740398e-01]
 [2.8084261e-07 1.3371173e-01 8.6628801e-01]
 [7.3911605e-07 1.7396419e-01 8.2603514e-01]
 [1.8682945e-07 5.5262547e-02 9.4473720e-01]
 [2.6708574e-06 2.4106367e-01 7.5893360e-01]]
     품종_setosa  품종_versicolor  품종_virginica
145          0              0             1
146          0              0             1
147          0              0             1
148          0              0             1
149          0              0             1


In [ ]:
print(model.get_weights())


[array([[ 0.83354527,  0.85431004, -0.1909224 ],
       [ 3.6865234 ,  0.29899508, -1.341348  ],
       [-3.6528873 , -0.23890005,  1.0906858 ],
       [-4.5346885 , -1.5115279 ,  3.0140512 ]], dtype=float32), array([ 2.3147864,  0.9122511, -1.7799255], dtype=float32)]


# 히든레이어 사용

In [ ]:
## 보스터 집 값 예측
# 과거의 데이터를 준비한다.
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv'
보스턴 = pd.read_csv(파일경로)

In [ ]:
#독립 종속 변수
print(보스턴.columns)

Index(['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat', 'medv'],
      dtype='object')


In [ ]:
독립 = 보스턴[['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat']]
종속 = 보스턴[['medv']]

print(독립.shape, 종속.shape)

(506, 13) (506, 1)


In [ ]:
#모델의 구조

X = tf.keras.layers.Input(shape = [13])
H = tf.keras.layers.Dense(10, activation='swish')(X)
Y = tf.keras.layers.Dense(1)(H)
model = tf.keras.models.Model(X,Y)
model.compile(loss = 'mse')

In [ ]:
#모델의 구조 확인
model.summary()

Model: "model_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_5 (InputLayer)         [(None, 13)]              0         
_________________________________________________________________
dense_4 (Dense)              (None, 10)                140       
_________________________________________________________________
dense_5 (Dense)              (None, 1)                 11        
Total params: 151
Trainable params: 151
Non-trainable params: 0
_________________________________________________________________


In [ ]:
#모델을 학습시킨다.
model.fit(독립, 종속, epochs = 1000, verbose= 0)

In [ ]:
model.fit(독립,종속, epochs =10)

Epoch 1/10
16/16 [==============================] - 0s 2ms/step - loss: 17.8662
Epoch 2/10
16/16 [==============================] - 0s 2ms/step - loss: 16.7307
Epoch 3/10
16/16 [==============================] - 0s 3ms/step - loss: 19.7640
Epoch 4/10
16/16 [==============================] - 0s 1ms/step - loss: 17.1507
Epoch 5/10
16/16 [==============================] - 0s 2ms/step - loss: 17.5065
Epoch 6/10
16/16 [==============================] - 0s 2ms/step - loss: 18.8180
Epoch 7/10
16/16 [==============================] - 0s 2ms/step - loss: 16.5997
Epoch 8/10
16/16 [==============================] - 0s 2ms/step - loss: 17.7829
Epoch 9/10
16/16 [==============================] - 0s 2ms/step - loss: 17.9527
Epoch 10/10
16/16 [==============================] - 0s 2ms/step - loss: 18.4920


In [ ]:
#모델을 이용한다. 
print(model.predict(독립[:5]))
print(종속[:5])

[[27.187101]
 [21.922152]
 [28.785568]
 [29.159775]
 [29.345797]]
   medv
0  24.0
1  21.6
2  34.7
3  33.4
4  36.2


In [ ]:
# 모델의 수식 확인
print(model.get_weights())

[array([[ 3.05854026e-02,  3.49304676e-01, -4.30271804e-01,
        -4.46885198e-01, -3.48364450e-02,  2.37130150e-01,
        -2.47215219e-02, -4.53657418e-01,  6.98571384e-01,
         1.61496460e-01],
       [-3.93082350e-01,  2.52198577e-01, -1.95649490e-01,
        -1.92226619e-01,  1.11410804e-01, -3.61797422e-01,
        -3.36353004e-01,  2.19851598e-01, -1.55592275e+00,
        -4.26657438e-01],
       [ 2.25150540e-01,  1.12639487e-01,  2.42677242e-01,
        -1.61762089e-01,  8.93076435e-02, -1.33465633e-01,
         5.04593626e-02, -1.99204966e-01, -2.11963341e-01,
         2.46057864e-02],
       [-1.64504778e+00,  3.96991909e-01,  1.09953843e-01,
        -1.81255829e+00,  1.18067086e+00, -1.97764802e+00,
         3.75029980e-03,  1.88797963e+00,  4.87499058e-01,
         1.32758200e+00],
       [ 1.08379507e+00, -3.82918835e-01, -1.07897855e-01,
         6.26855075e-01, -7.50442073e-02,  1.01812327e+00,
        -3.58339787e-01, -9.84385431e-01, -6.08968675e-01,
        -5

# 아이리스 품종 분류 using 히든레이어

In [1]:
#라이브러리 
import pandas as pd
import tensorflow as tf

In [2]:
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
아이리스 = pd.read_csv(파일경로) 

In [3]:
아이리스.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa

In [4]:
#원핫인코딩 
인코딩 = pd.get_dummies(아이리스)

In [6]:
print(인코딩.columns)
인코딩.head()

Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종_setosa', '품종_versicolor',
       '품종_virginica'],
      dtype='object')


꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0   5.1  3.5    1.4   0.2          1              0             0
1   4.9  3.0    1.4   0.2          1              0             0
2   4.7  3.2    1.3   0.2          1              0             0
3   4.6  3.1    1.5   0.2          1              0             0
4   5.0  3.6    1.4   0.2          1              0             0

In [7]:
#독립, 종속 변수
독립 = 인코딩[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속 = 인코딩[['품종_setosa', '품종_versicolor','품종_virginica']]

print(독립.shape, 종속.shape)

(150, 4) (150, 3)


In [14]:
# 모델의 구조를 만든다.
X = tf.keras.layers.Input(shape=[4])
H = tf.keras.layers.Dense(8, activation = 'swish')(X)
H = tf.keras.layers.Dense(8, activation='swish')(H)
H = tf.keras.layers.Dense(8,activation='swish')(H)
Y = tf.keras.layers.Dense(3,activation='softmax')(H)
model = tf.keras.models.Model(X,Y)
model.compile(loss='categorical_crossentropy', metrics='accuracy')


In [15]:
#모델의 구조 확인
model.summary()

Model: "model_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_3 (InputLayer)         [(None, 4)]               0         
_________________________________________________________________
dense_8 (Dense)              (None, 8)                 40        
_________________________________________________________________
dense_9 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_10 (Dense)             (None, 8)                 72        
_________________________________________________________________
dense_11 (Dense)             (None, 3)                 27        
Total params: 211
Trainable params: 211
Non-trainable params: 0
_________________________________________________________________


In [16]:
#데이터로 모델을 학습시킨다.
model.fit(독립, 종속, epochs=100)

Epoch 1/100
5/5 [==============================] - 1s 3ms/step - loss: 3.5178 - accuracy: 0.3346
Epoch 2/100
5/5 [==============================] - 0s 2ms/step - loss: 2.6488 - accuracy: 0.3325
Epoch 3/100
5/5 [==============================] - 0s 2ms/step - loss: 2.7638 - accuracy: 0.3372
Epoch 4/100
5/5 [==============================] - 0s 2ms/step - loss: 2.5305 - accuracy: 0.3338
Epoch 5/100
5/5 [==============================] - 0s 2ms/step - loss: 2.2253 - accuracy: 0.3160
Epoch 6/100
5/5 [==============================] - 0s 2ms/step - loss: 2.0302 - accuracy: 0.3403
Epoch 7/100
5/5 [==============================] - 0s 3ms/step - loss: 1.8381 - accuracy: 0.3602
Epoch 8/100
5/5 [==============================] - 0s 3ms/step - loss: 1.7762 - accuracy: 0.3121
Epoch 9/100
5/5 [==============================] - 0s 2ms/step - loss: 1.5313 - accuracy: 0.2951
Epoch 10/100
5/5 [==============================] - 0s 2ms/step - loss: 1.3570 - accuracy: 0.3481
Epoch 11/100
5/5 [===========

In [17]:
print(model.predict(독립[:5]))
print(종속[:5])

[[9.9993765e-01 1.8096009e-05 4.4214190e-05]
 [9.9985814e-01 4.9300299e-05 9.2439914e-05]
 [9.9984503e-01 5.3685460e-05 1.0127602e-04]
 [9.9963641e-01 1.5935661e-04 2.0424850e-04]
 [9.9992597e-01 2.2662196e-05 5.1350817e-05]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0
